## Calculate the mean,median,mode,standard deviation and variance for the given dataset:

## [5,10,15,20,25,30,35]

In [5]:
import numpy as np
import statistics as stats

In [2]:
data=np.array([5,10,15,20,25,30,35])

In [6]:
mean = stats.mean(data)
median = stats.median(data)
mode = stats.mode (data)
std = stats.stdev(data)
var = stats.variance(data)

In [7]:
print(f"The mean of the given data is: {mean}")
print(f"The median of the given data is: {median}")
print(f"The mode of the given data is: {mode}")
print(f"The standard deviation of the given data is: {std}")
print(f"The variance of the given data is: {var}")

The mean of the given data is: 20
The median of the given data is: 20
The mode of the given data is: 5
The standard deviation of the given data is: 10.770329614269007
The variance of the given data is: 116


## Generate a random data set of size 100 with values between 1 and 50. Calculate all the statistical measures discussed above.

In [11]:
import numpy as np
import statistics as stats

In [10]:
data = np.random.uniform(1,51,size=100)

In [13]:
mean = stats.mean(data)
median = stats.median(data)
mode = stats.mode(data)
std = stats.stdev(data)
var = stats.variance(data)

In [15]:
print(f"The mean of the given data is: {mean}")
print(f"The median of the given data is: {median}")
print(f"The mode of the given data is: {mode}")
print(f"The standard deviation of the given data is: {std}")
print(f"The variance of the given data is: {var}")

The mean of the given data is: 24.57481802060442
The median of the given data is: 25.13818722376311
The mode of the given data is: 44.53426559955646
The standard deviation of the given data is: 13.520015851940704
The variance of the given data is: 182.79082863672792


## Create a 5x5 array filled with random integers from 0 to 10.

In [38]:
import numpy as np

In [40]:
matrix = np.random.randint(0,11,size=(5,5))

In [41]:
matrix

array([[10,  6, 10,  5,  2],
       [ 9,  9, 10,  6, 10],
       [ 6,  1,  2,  1,  2],
       [ 6,  0,  8,  6,  3],
       [ 9,  8,  9,  2,  9]])

In [42]:
row = np.random.randint(0,11,size=(5))

In [43]:
row

array([9, 8, 8, 6, 3])

In [44]:
newMatrix = matrix + row

In [45]:
newMatrix

array([[19, 14, 18, 11,  5],
       [18, 17, 18, 12, 13],
       [15,  9, 10,  7,  5],
       [15,  8, 16, 12,  6],
       [18, 16, 17,  8, 12]])

In [47]:
productMatrix = newMatrix*row

In [48]:
productMatrix

array([[171, 112, 144,  66,  15],
       [162, 136, 144,  72,  39],
       [135,  72,  80,  42,  15],
       [135,  64, 128,  72,  18],
       [162, 128, 136,  48,  36]])

## Array Manipulation

In [33]:
import numpy as np
import statistics as stats

In [27]:
data = np.random.randint(1,21,size=(20))

In [28]:
data

array([ 3, 15, 10,  2,  3,  9, 12, 14, 20,  6, 20, 16,  4, 14, 12, 13, 16,
       20, 13,  3])

In [29]:
reshapedData = np.reshape(data,(4,5))

In [30]:
reshapedData

array([[ 3, 15, 10,  2,  3],
       [ 9, 12, 14, 20,  6],
       [20, 16,  4, 14, 12],
       [13, 16, 20, 13,  3]])

In [31]:
reshapedData2 = np.reshape(reshapedData,(20))

In [37]:
reshapedData2

array([ 3, 15, 10,  2,  3,  9, 12, 14, 20,  6, 20, 16,  4, 14, 12, 13, 16,
       20, 13,  3])

In [35]:
mean = stats.mean(reshapedData2)
median = stats.median(reshapedData2)
mode = stats.mode(reshapedData2)
std = stats.stdev(reshapedData2)
var = stats.variance(reshapedData2)

In [36]:
print(f"The mean of the given data is: {mean}")
print(f"The median of the given data is: {median}")
print(f"The mode of the given data is: {mode}")
print(f"The standard deviation of the given data is: {std}")
print(f"The variance of the given data is: {var}")

The mean of the given data is: 11
The median of the given data is: 12.5
The mode of the given data is: 3
The standard deviation of the given data is: 6.0
The variance of the given data is: 36
